# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/z0x6vm2fcmbvd2vk7i3lqg342pb5vvfi-hm-session-vars.fish/etc/profile.d/hm-session-vars.fish

# Source handler functions

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases

    # Interactive shell initialisation
    /nix/store/nrfxnpgn8m6cvcgsdwhix7pd8z27vd7w-zoxide-0.9.9/bin/zoxide init fish | source

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/szymon/.local/share/fish/home-manager/generated_completions" $post
    end

    /nix/store/h2rh9c9sa6fiix2xr4jbll7wsji0jxvi-atuin-18.11.0/bin/atuin init fish | source

    # no dum greeting
    set fish_greeting ""

    # yes, please setup git for me
    gh auth setup-git

    # add github ssh key
    # (dodałem przekierowanie błędów, żeby nie śmieciło na ekranie przy starcie)
    eval (ssh-agent -c) >/dev/null
    ssh-add ~/.ssh/github 2>/dev/null

    # add github gpg key
    set -gx GPG_TTY (tty)

    # vi mode
    fish_vi_key_bindings

    # Odpalenie fastfetcha na start
    clear
    fastfetch --config ~/.config/fastfetch/startup.jsonc

end
