[mgr]
linemode = "none"
mouse_events = ["click", "scroll"]
ratio = [1, 4, 3]
scrolloff = 5
show_hidden = false
show_symlink = true
sort_by = "alphabetical"
sort_dir_first = true
sort_reverse = false
sort_sensitive = false
sort_translit = false
title_format = "Yazi: {cwd}"
